/**
 * Switch Database REST API
 * Switch API is the primary endpoint of data sevices and Switch DB's platform. You can do adding, editing, deleting or listing data works to your database with query operations by using this low-level API based on HTTP.
 *
 * OpenAPI spec version: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ListOrder {
  
  @SerializedName("type")
  private String type = null;
  @SerializedName("by")
  private String by = null;

  /**
   * Order types: ASC, DESC
   **/
  @ApiModelProperty(value = "Order types: ASC, DESC")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   * Column name.
   **/
  @ApiModelProperty(value = "Column name.")
  public String getBy() {
    return by;
  }
  public void setBy(String by) {
    this.by = by;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListOrder listOrder = (ListOrder) o;
    return (this.type == null ? listOrder.type == null : this.type.equals(listOrder.type)) &&
        (this.by == null ? listOrder.by == null : this.by.equals(listOrder.by));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.by == null ? 0: this.by.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListOrder {\n");
    
    sb.append("  type: ").append(type).append("\n");
    sb.append("  by: ").append(by).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
